name: QA Test Management CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pytest --alluredir=allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots

  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g newman newman-reporter-html
      - name: Run Postman tests
        run: newman run postman/collection.json -e postman/environment.json -r cli,html --reporter-html-export newman_report.html
      - uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman_report.html
